# Generated by Django 3.2.4 on 2021-06-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_alter_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='satrt_date',
            new_name='start_date',
        ),
    ]
