# Generated by Django 3.2.4 on 2021-06-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_userquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='UserAnswer',
        ),
    ]
