# Generated by Django 3.2.4 on 2021-06-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0006_rename_userquestion_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_of_users', to='poll_app.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
