# Generated by Django 3.2.4 on 2021-06-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0010_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='answers',
        ),
    ]
